create table tb_records (id int8 generated by default as identity, date date not null, description varchar(255), record_status int4 not null, record_type int4 not null, value float4 not null, user_id int8 not null, primary key (id));
create table tb_users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id));
alter table if exists tb_users add constraint UK_grd22228p1miaivbn9yg178pm unique (email);
alter table if exists tb_records add constraint FKe883j248cnpyeq4t790s7mtd5 foreign key (user_id) references tb_users;
